name: Push

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: make build-in-docker

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: sweat-hero
          path: res/sweat_hero.wasm

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Lint
        run: make lint

  unit-tests:
    needs: [ build, lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Unit tests
        run: make test

  integration-tests:
    needs: [ build, lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Integration tests
        run: make integration

  push:
    needs: [ unit-tests, integration-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: sweat-hero
          path: res/

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: Updated binary
          branch: main
          github_token: ${{ secrets.ACTIONS_TOKEN }}
